# Generated by Django 5.2.11 on 2026-02-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(help_text='Starting city', max_length=255)),
                ('pickup_location', models.CharField(help_text='Pickup city', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Dropoff city', max_length=255)),
                ('current_cycle_used', models.FloatField(default=0, help_text='Hours already used in the 70-hour/8-day rolling cycle')),
                ('total_distance_km', models.FloatField(blank=True, help_text='Total route distance in km', null=True)),
                ('total_duration_hours', models.FloatField(blank=True, help_text='Total driving duration in hours', null=True)),
                ('route_geometry', models.JSONField(blank=True, help_text='Route polyline coordinates', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('fuel', 'Fuel Stop'), ('rest', 'Rest Stop'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('restart', '34-Hour Restart')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_from_start_km', models.FloatField(default=0, help_text='Distance from trip start in km')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['distance_from_start_km'],
            },
        ),
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date this log covers')),
                ('events', models.JSONField(default=list, help_text='List of events: [{"type": "driving", "start": "06:00", "end": "14:00"}, ...]')),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('cycle_hours_remaining', models.FloatField(default=70)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_days', to='trips.trip')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
